name: Connect to EC2 instance

on:
  push:
    branches:
      - master

jobs:
  connect-to-ec2:
    name: Connect to EC2 instance
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      EC2_SECURITY_GROUP_ID: sg-0247107399b909b0e
      WORK_DIR: /home/${{ secrets.EC2_USERNAME }}/${{ secrets.EC2_HOST }}
      HOST: ${{ github.event.repository.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::497780720908:role/johndusel-github-oidc-provider-Role-GVUK6BLT9IMY
          aws-region: us-east-2

      - name: Get runner IP address
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Whitelist runner IP address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $EC2_SECURITY_GROUP_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Write SSH key to runner
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/gh_actions_johndusel
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/gh_actions_johndusel

      - name: Connect to EC2 instance
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo apt-get update && sudo apt-get upgrade -y
            cd ${{ secrets.EC2_HOST }}
            eval `ssh-agent -s` && ssh-add ~/.ssh/extreme_pem_aws_20220814.pem && echo `ssh-add -l`
            git switch master
            git pull

      - name: Revoke runner IP address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $EC2_SECURITY_GROUP_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Remove SSH key from runner
        run: |
          rm -rf ~/.ssh
