name: Connect to EC2 instance

on:
  push:
    branches:
      - "master"
      - "cd/**"

jobs:
  connect-to-ec2:
    name: Connect to EC2 instance
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      EC2_SECURITY_GROUP_ID: sg-0247107399b909b0e
      REPO_DIR: /home/${{ secrets.EC2_USERNAME }}/${{ secrets.EC2_HOST }}
      OPT_DIR: /opt/${{ secrets.EC2_HOST }}
      VENV_DIR: /opt/${{ secrets.EC2_HOST }}/backend/.venv
      CONF_DIR: /etc/opt/${{ secrets.EC2_HOST }}
      DJANGO_BASE_DIR: /opt/${{ secrets.EC2_HOST }}/backend
      STATICFILES_DIR: /var/opt/${{ secrets.EC2_HOST }}/staticfiles
      NEXTJS_BASE_DIR: /opt/${{ secrets.EC2_HOST }}/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::497780720908:role/johndusel-github-oidc-provider-Role-GVUK6BLT9IMY
          aws-region: us-east-2

      - name: Get runner IP address
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Whitelist runner IP address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $EC2_SECURITY_GROUP_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.GH_DEPLOY_PRIVATE_KEY }}

      - name: Write SSH key to runner
        run: |
          mkdir -p ~/.ssh
          echo '${{ secrets.EC2_PRIVATE_KEY }}' > ~/.ssh/gh_deploy_johndusel
          chmod 600 ~/.ssh/gh_deploy_johndusel
          ssh-keyscan -H ${{ secrets.EC2_HOST }} > ~/.ssh/known_hosts

      - name: Pull code from GitHub
        run: |
          ssh -A -i ~/.ssh/gh_deploy_johndusel ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }} "sudo apt-get update && sudo apt-get upgrade -y && cd $REPO_DIR && git switch master && git pull"

      - name: Copy to /opt and change permissions
        run: |
          ssh -A -i ~/.ssh/gh_deploy_johndusel ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }} "sudo cp --recursive --update --preserve $REPO_DIR /opt && sudo chown -R root:root $OPT_DIR && sudo chmod 0755 $OPT_DIR"

      - name: Install Python dependencies
        run: |
          ssh -A -i ~/.ssh/gh_deploy_johndusel ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }} "ENV_PATH=$CONF_DIR/.env PYTHONPATH=$CONF_DIR:$DJANGO_BASE_DIR sudo $VENV_DIR/bin/pip install -r $DJANGO_BASE_DIR/requirements.txt"

      - name: Python manage.py migrate
        run: |
          ssh -A -i ~/.ssh/gh_deploy_johndusel ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }} "sudo ENV_PATH=$CONF_DIR/.env PYTHONPATH=$CONF_DIR:$DJANGO_BASE_DIR DJANGO_SETTINGS_MODULE=settings $VENV_DIR/bin/python $DJANGO_BASE_DIR/manage.py migrate --noinput"

      - name: Python manage.py collectstatic
        run: |
          ssh -A -i ~/.ssh/gh_deploy_johndusel ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }} "sudo ENV_PATH=$CONF_DIR/.env PYTHONPATH=$CONF_DIR:$DJANGO_BASE_DIR DJANGO_SETTINGS_MODULE=settings $VENV_DIR/bin/python $DJANGO_BASE_DIR/manage.py collectstatic --noinput"

      - name: Chown static files
        run: |
          ssh -A -i ~/.ssh/gh_deploy_johndusel ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }} "sudo chown -R ${{ secrets.EC2_HOST }}:${{ secrets.EC2_HOST }} $STATICFILES_DIR"

      - name: Restart Next.js server (install dependencies, start Next.js server)
        run: |
          ssh -A -i ~/.ssh/gh_deploy_johndusel ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }} "sudo systemctl restart nextjs-${{ secrets.EC2_HOST }} || sudo systemctl start nextjs-${{ secrets.EC2_HOST }}"

      - name: Restart gunicorn
        run: |
          ssh -A -i ~/.ssh/gh_deploy_johndusel ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} -p ${{ secrets.EC2_PORT }} "sudo systemctl restart gunicorn-${{ secrets.EC2_HOST }} || sudo systemctl start gunicorn-${{ secrets.EC2_HOST }}"

      - name: Revoke runner IP address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $EC2_SECURITY_GROUP_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Remove SSH key from runner
        run: |
          rm -rf ~/.ssh
